config/routes.rb
Contenteditable::Engine.routes.draw do
  put "update" => "contents#update"
end

app/models/contenteditable/translation.rb
module Contenteditable
  class Translation < ActiveRecord::Base
    attr_accessible :key, :value
    self.table_name = "translations"
  end
end

app/controllers/contenteditable/application_controller.rb
module Contenteditable
  class ApplicationController < ActionController::Base
  end
end

app/controllers/contenteditable/contents_controller.rb
require_dependency "contenteditable/application_controller"

module Contenteditable
  class ContentsController < ApplicationController
    include ApplicationHelper

    before_filter :filter_for_ce

    def update
      params[:translations].each do |p|
        I18n.backend.store_translations(
          params[:locale] || "en", {p[0] => p[1]}, :escape => false)
      end
      head :status => 204
    end

    private
    def filter_for_ce
      head :status => 401 unless is_authorized?
    end
  end
end

app/helpers/contenteditable/application_helper.rb
module Contenteditable
  module ApplicationHelper

    def ceditable(key, tag="span", html_options={})
      params[:locale] ||= "en"
      content = I18n.t(key)

      if is_authorized?
        html_options.merge!(:contenteditable => true, "data-tag" => key)
      end
      content_tag(tag, content, html_options)
    end

    def contenteditable_assets
      if is_authorized?
        a=javascript_include_tag "contenteditable/contenteditable"
        b=stylesheet_link_tag    "contenteditable/contenteditable", :media => "all"
        c = a + b
        c
      end
    end

    def save_button
      if is_authorized?
        render "contenteditable/tools/save_button"
      end
    end

    def is_authorized?
      if Contenteditable::Engine.ce_filter.present?
        main_app.scope.send(Contenteditable::Engine.ce_filter)
      else
        true
      end
    end

  end
end

app/helpers/contenteditable/contents_helper.rb
module Contenteditable
  module ContentsHelper
  end
end

app/views/contenteditable/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_area :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contenteditable/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contenteditable/contents/index.html.erb
<h1>Listing contents</h1>

<table>
  <tr>
    <th>Key</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contents.each do |content| %>
  <tr>
    <td><%= content.key %></td>
    <td><%= content.value %></td>
    <td><%= link_to 'Show', content %></td>
    <td><%= link_to 'Edit', edit_content_path(content) %></td>
    <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Content', new_content_path %>

app/views/contenteditable/contents/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contenteditable/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Key:</b>
  <%= @content.key %>
</p>

<p>
  <b>Value:</b>
  <%= @content.value %>
</p>


<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/contenteditable/tools/_save_button.html.erb
<div class="contenteditable_save_button">

  This is the Save button!

</div>

app/views/layouts/contenteditable/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contenteditable</title>
  <%= stylesheet_link_tag    "contenteditable/application", :media => "all" %>
  <%= javascript_include_tag "contenteditable/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>